### ISSUE TITLE
PDA owned storage accounts

### ISSUE THREAD

**Issue by KultureElectric** [GenesysGo/shadow-drive#72]
## PDA owned storage-accounts

I would love to start an open discussion of how storage accounts could be owned by PDAs.

At the moment this is not possible. To upload, edit and delete files we need to make a call to the Shdw-drive API. We need to pass a signature by the owner of the storage-account we want to make the action to.

We can't directly invocate an action from a program so we must do it from a client. But we can't just get a PDA signature to be passed in the API request either.

### The Problem
Imagine you want to design a solana program that in which accounts need to store some data. Not everything must be on the blockchain and for costs purposes you decide that a field of the on-chain account points to a file hosted on the SHDW drive. Like the metadata_uri field in a metaplex metadata account. Or wordcel linking the actual content of an article.

At the moment doing this would require a normal keypair that has the authority over the storage-account we want to upload to. Then we could make our own front-end and do the logic from there. Uploading from the front-end and therefore ensuring that the uploaded file that is linked in the program account is correct.
-> This makes the use of the program only possible from one centralized front-end which defeats the purpose of using Shdw.

### Potential Solution
Uploading and all other actions will only be possible through a client, there's nothing we can do here. But we could come up with a solution that the API can have something else than a signature as way to confirm an upload.

An attestation that a program can produce for a PDA that has the authority over the storage-account. That can then be passed in the upload API call to authorize it. 

Helmet face on discord had the idea that the program with the authority PDA could have an instruction create a transaction that logs the operation that should be done. The transaction signature could be passed into the API call. On the backend the Shdw Drive would need to confirm that transaction and make it invalid after a single action performed.

----

Maybe there are other ways as well how something like this could be achieved. Let's discuss!

**Comment by ebrightfield** [comment]
Let's distill the problem here a bit.

#### Goal:
For fully program-driven usage of Shadow Drive, including:
- Creating and managing storage accounts
- Uploading and deleting files.

#### What's Easy to Do?
Any of the purely on-chain operations are doable, which basically encompasses the entire first bullet, i.e. storage account creation / management. Programmers will have to decide how exactly they'd like to provide the funds, etc, but this all basically can be done OOB.

#### What's Hard to Do?
Anything in the second bullet regarding uploading files, deleting them, editing them, etc. It's hard for two reasons:
1. PDAs do not produce cryptographic signatures, therefore the "off-chain Web3 signature" style of request validation doesn't apply for programs.
2. The whole interaction with Shadow Drive with respect to actual files takes place off-chain. There's not an obvious, general way to make a file known to a program, and for a program to essentially make the HTTP calls necessary to Shadow Drive.

#### A Possible Solution
- For off-chain operations like e.g. uploading a file, some PDA can be stored with a message that describes all pertinent details about the file to be uploaded, its hash, etc.
- Once this PDA is created, anyone with the actual file could upload it.

#### The Lingering Problem with the Above Solution
How do you know if/when you can delete a PDA that is authorizing some file upload? The on-chain storage account's usage metrics are updated as files are uploaded, but there is no way to disambiguate which file caused which particular update.
I'm not sure this could be solved with any degree of high assurance.

**Comment by tracy-codes** [comment]
Hi,

Unfortunately this cannot be done with the current architecture as a PDA can't emit a signature like a wallet can. A few users have tried to implement this with no avail. We will keep this type of functionality in mind for Shadow Drive V2, but currently it's not possible.
